### ISSUE TITLE
Readme Updated

### ISSUE THREAD

**Issue by formanite21** [ihamzazahid/AEAS#15]
This Automation Entrance authorization system is based on Python Programming Language embedded on Raspberry Pi 4 with Raspbian OS installed in it with integration of hardware modules and sensors including LEDs, Motion Sensor, Servo Motor, Temperature Sensor, Male-to-male ,Female-to-female and male-to-female wires and camera module. The purpose of this System is to give a contactless entry without any physical contact. The main features of the product are:

Facial Recognition
Mask Detection
Temperature Measurement

**Comment by ihamzazahid** [comment]
this fixes #15
